[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = []

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_URL}"

[etherscan]
base-sepolia = { key = "${API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=84532" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options